formspree_form_id: formspree_form_id
name: 对酒当歌
title: 网盘资源分享博客
description: 用于分享一些储存在网络云盘里的资源
tags:
  - 阿里云盘
  - 阿里云盘资源
  - 对酒当歌
  - 分享
  - 影视资源
show_hero: true
paginate: 25
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: jaygny@qq.com
disqus_username: disqus_username
