formspree_form_id: formspree_form_id
name: 对酒当歌
title: 网盘资源分享博客
description: 用于分享一些储存在网络云盘里的资源
tags:
  - 阿里云盘
  - 阿里云盘资源
  - 对酒当歌
  - 分享
  - 影视资源
show_hero: true
paginate: 25
menu:
  - title: 首页
    url: /
  - title: 关于
    url: /about
  - title: 联系
    url: /contact
  - title: rss地图
    url: /feed.xml
  - url: /123
    title: "123"
email: jaygny@qq.com
disqus_username: disqus_username
